#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := SSD1351.cpp color.cpp game.cpp gameObject.cpp bike.cpp wall.cpp gameLogic.cpp AIBike.cpp

# header files in this project
HEADERS := SSD1351.hpp color.hpp game.hpp gameObject.hpp bike.hpp wall.hpp gameLogic.hpp AIBike.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
