#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := AIBike.cpp bike.cpp color.cpp game.cpp gameLogic.cpp gameObject.cpp SSD1351.cpp wall.cpp

# header files in this project
HEADERS := AIBike.hpp bike.hpp color.hpp game.hpp gameLogic.hpp gameObject.hpp SSD1351.hpp wall.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.native
